names<-c("alice","bob","diana","ethan")
ages<-c(25,30,22,28)
gender<-c("F","M","F","M")
scores<-c(85,90,78,88)
students_df<-data.frame(Name=names,Age=ages,Gender=gender,Score=scores)
cat("original Data frame:\n")
print(students_df)
cat("\n Scores Column:\n")
print(students_df$Score)
students_df$Result<-ifelse(students_df$Score>=80,"pass","fail")
cat("\n Updated Data frame:\n")
print(students_df)
cat("\n summary of Data frame:\n")
print(summary(students_df))
